name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Add-on lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Home Assistant add-on linter
        uses: frenck/action-addon-linter@v2
        with:
          path: "./redalert"

  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test-build image (${{ matrix.arch }})
        uses: home-assistant/builder@2024.03.5
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/redalert \
            --image "local/{arch}-addon-redalert" \
            --docker-hub-check false \
            --test \
            --addon
